/**
 * colleges.js — x0s College Data
 *
 * Format per entry:
 * {
 * id:      'E001',            
 * name:    'College Name, Location',  
 * pfp:     'college.png',     
 * pill1:   'Cutoff 2025',    
 * pill2:   'KCET 2025',      
 * }
 */

window.XOS_COLLEGES = [
  { id: 'E001', name: 'Univesity of Visvesvaraya College of Engineering, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E002', name: 'Govt.S K S J T Institute of Engineering, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E003', name: 'B M S College of Engineering, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E004', name: 'Dr. Ambedkar Institute of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E005', name: 'R. V. College of Engineering, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E006', name: 'M S Ramaiah Institute of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E007', name: 'Dayananda Sagar College of Engineering, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E008', name: 'Bangalore Institute of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E009', name: 'PES University, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E011', name: 'M V J College of Engineering, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E012', name: 'Sir M.Visvesvaraya Institute of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E013', name: 'Ghousia Engineering College, Ramanagara', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E014', name: 'S J C Institute of Technology, Chickkaballapur', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E015', name: 'Dr.T.Thimmaiah Institute of Technology, KGF', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E016', name: 'Siddaganga Institute of Technology, Tumkur', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E017', name: 'Sri Siddhartha Institute of Technology, Tumkur', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E018', name: 'Kalpatharu Institute of Technology, Tiptur', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E021', name: 'Sri Jayachamarajendra College of Engineering, Mysore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E022', name: 'The National Institute of Engineering (South), Mysore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E023', name: 'P E S College of Engineering, Mandya', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E024', name: 'Malnad College of Engineering, Hassan', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E028', name: 'Tontadarya College of Engineering, Gadag', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E029', name: 'Maratha Mandal Engineering College, Belgaum', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E031', name: 'Basaveshwara Engineering College, Bagalkote', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E032', name: 'Rural Engineering College, Hulkoti', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E033', name: 'Sri Taralabalu Jagadguru Institute of Technology, Ranebennur', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E034', name: 'SDM College of Engineering, Dharwad', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E035', name: 'Anjuman Institute of Technology & Management, Bhatkal', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E036', name: 'K L E Technological Univeristy, Belgaum', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E037', name: 'K.L.S. Gogte Institute of Technology, Belgaum', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E038', name: 'BLDEA\'s VP Dr.P.G. Hallakatti College, Bijapur', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E040', name: 'Hira Sugar Institute of Technology, Nidasoshi', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E041', name: 'P D A College of Engineering, Gulbarga', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E042', name: 'Khaja Bandanawaz University, Kalaburagi', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E043', name: 'Gurunanak Dev Engineering College, Bidar', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E044', name: 'Bheemanna Khandre Institute of Technology, Bhalki', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E045', name: 'Rao Bahadur Y.Mahabaleswarappa Engineering College, Bellary', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E046', name: 'Sir M Visvesvaraya College of Engineering, Raichur', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E047', name: 'Malnad College of Engineering, Hassan', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E048', name: 'B M S College of Engineering, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E049', name: 'Basaveshwara Engineering College, Bagalkote', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E054', name: 'K V G College of Engineering, Sullia', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E055', name: 'P A College of Engineering, Mangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E056', name: 'The National Institute of Engineering, Mysore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E057', name: 'JSS Science and Technology University, Mysuru', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E058', name: 'P E S College of Engineering, Mandya', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E059', name: 'P D A College of Engineering, Gulbarga', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E060', name: 'Dr. Ambedkar Institute of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E061', name: 'University B.D.T College of Engineering, Davanagere', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E062', name: 'Bapuji Institute of Engineering & Technology, Davangere', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E063', name: 'S J M Institute of Technology, Chitradurga', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E064', name: 'Adhichunchanagiri Institute of Technology, Chickamagalur', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E065', name: 'Jawaharlal Nehru New College of Engineering, Shimoga', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E066', name: 'University B.D.T. college of Engineering, Davanagere', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E070', name: 'Bahubali College of Engineering, Hassan', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E071', name: 'Vidya Vardhaka College of Engineering, Mysore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E075', name: 'Ballari Institute of Technology & Management, Bellary', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E076', name: 'Proudadevaraya Institute of Technology, Hospet', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E077', name: 'Vidya Vikas Institute of Engineering & Technology, Mysore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E078', name: 'The Oxford College of Engineering, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E079', name: 'Acharya Institute of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E081', name: 'SRI SIDDHARTHA SCHOOL OF ENGINEERING, TUMKUR', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E082', name: 'J S S Academy of Technical Education, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E083', name: 'H.K.B.K.College of Engineering, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E085', name: 'APS College of Engineering, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E086', name: 'Sri Sairam College Of Engineering, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E087', name: 'Vivekananada Institute of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E090', name: 'Sri Revana Siddeswara Institute of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E091', name: 'K S Institute of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E092', name: 'Vemana Institute of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E093', name: 'Basavakalyana Engineering College, Bidar', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E094', name: 'Coorg Institute of Technology, Ponnampet', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E095', name: 'AMC Engineering College, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E096', name: 'East Point College of Engineering & Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E097', name: 'C M R Institute of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E098', name: 'Atria Institute of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E099', name: 'New Horizon College of Engineering, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E100', name: 'K N S Institute of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E101', name: 'Channabasaveshwara Institute of Technology, Tumkur', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E102', name: 'DONBOSCO Institute of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E103', name: 'Global Academy of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E104', name: 'Nagarjuna College of Engineering, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E106', name: 'East West Institute Of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E107', name: 'B N M Institute of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E108', name: 'SAPTHAGIRI NPS UNIVERISTY, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E109', name: 'City Engineering College, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E111', name: 'Sri Venkateshwara College of Engineering, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E112', name: 'Sri Krishna Institute of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E113', name: 'Sambhram Institute of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E114', name: 'G M Institute of Technology, Davanagere', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E115', name: 'S.J B. Institute of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E116', name: 'R.L.Jalappa Institute of Technology, Doddaballapura', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E118', name: 'RNS Institute of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E119', name: 'K C T Engineering College, Gulbarga', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E120', name: 'Jnanavikasa Institute of Technology, Ramanagar', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E121', name: 'Vivekananada College of Engineering, Puttur', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E123', name: 'Canara Engineering College, Bantwal', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E124', name: 'Rajiv Gandhi Institute of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E126', name: 'B M S Institute of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E127', name: 'M S Engineering College, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E128', name: 'Sharanbasava University, Kalaburagi', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E129', name: 'St.Joseph Engineering College, Mangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E130', name: 'Shridevi Institute of Engineering, Tumkur', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E132', name: 'Secab Institute of Engineering, Bijapur', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E133', name: 'G S S S Institute for Women, Mysore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E134', name: 'Smt. Kamala & Sri Venkappa M.Agadi College, Gadag', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E135', name: 'K L S Viswanathrao Deshpande Institute, Haliyal', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E136', name: 'Moodalakatte Institute of Technology, Udupi', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E139', name: 'Impact College of Engineering, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E141', name: 'PES UNIVERSITY (Electronic City), Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E142', name: 'Adhichunchanagiri University, Mandya', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E144', name: 'Srinivas Institute of Technology, Mangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E145', name: 'Rajarajeswari College of Engineering, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E146', name: 'Shreedevi Institute of Technology, Mangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E147', name: 'T.John Institute of technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E149', name: 'Cambridge Institutute of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E150', name: 'P E S Institute of Technology, Shimoga', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E151', name: 'Mangalore Institute of Technology, Mangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E152', name: 'S D M Institute of Tech., Dakshina Kannada', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E153', name: 'S E A College of Engineering, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E154', name: 'Government Engineering College, Chamarajanagara', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E155', name: 'Government Engineering College, Hassan', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E156', name: 'Government Engineering College, Mandya', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E157', name: 'Government Engineering College, Ramanagaram', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E158', name: 'Maharaja Institute of Technology, Mysore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E159', name: 'Karavali Institute of Technology, Mangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E160', name: 'Sahyadri College of Engineering, Mangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E161', name: 'Government Engineering College, Kushalanagar', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E162', name: 'Government Engineering College, Raichur', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E163', name: 'Government Engineering College, Haveri', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E164', name: 'Government Engineering College, Hoovina Hadagali', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E165', name: 'Yenepoya Institute Of Technology, Mangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E167', name: 'K L E S\'s College of Engineering, Belgaum', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E168', name: 'Amrutha Institute (AIEMS), Ramanagar', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E169', name: 'Alva\'s Institute of Engineering, Moodabidre', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E171', name: 'Brindavan College of Engineering, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E172', name: 'R.R. Institute of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E173', name: 'Sai Vidya Institute of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E174', name: 'Dr. S.S.S. Mahaswamyji College, Bangalore Rural', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E175', name: 'S.S.E.T.S.S.G. Balekundri Institute, Belgaum', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E176', name: 'Navodaya Institute of Technology, Raichur', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E177', name: 'Rajeev Institute of Technology, Hassan', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E178', name: 'The National Institute of Engineering (North), Mysuru', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E180', name: 'Beary\'s Institute of Technology, Mangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E181', name: 'Sri Basaveswara Institute of Technology, Tiptur', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E184', name: 'C Byre Gowda Institute, Kolar', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E185', name: 'Angadi Institute of Technology, Belgaum', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E186', name: 'ACS College of Engineering, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E188', name: 'Vijaya Vittala Institute, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E189', name: 'NAVKIS COLLEGE OF ENGINEERING, Hassan', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E191', name: 'Akshaya Institute of Technology, Tumkur', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E193', name: 'Srinivas University, Mangaluru', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E194', name: 'Government Engineering College, Karwar', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E196', name: 'Jain College of Engineering, Belgaum', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E197', name: 'Veerappa Nisty Engineering College, Yadigir', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E198', name: 'Sharanbasava University for Women, Kalaburagi', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E199', name: 'AGM Rural Engineering College, Hubli', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E201', name: 'Gopalan College of Engineering, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E202', name: 'Sampoorna Group of Institutions, Ramanagara', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E203', name: 'K S School of Engineering, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E204', name: 'Bangalore Technological Institute, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E205', name: 'ATME College of Engineering, Mysore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E206', name: 'Shri Madhwa Vadiraja Institute, Udupi', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E207', name: 'Somashekhar R Kothiwale Institute, Nippani', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E209', name: 'Jyothi Institute of Technology, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E210', name: 'G Madegowda Institute, Mandya', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E211', name: 'Jain Institute of Technology, Davanagere', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E212', name: 'Dayananda Sagar Academy (DSATM), Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E213', name: 'Lingarajappa Engineering College, Bidar', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E216', name: 'Shetty Institute of Technology, Gulbarga', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E220', name: 'ALLIANCE University Central Campus, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E221', name: 'Biluru Gurubasava Institute, Mudhol', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E222', name: 'Cambridge Institute (North), Devanahalli', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E227', name: 'Cauvery institute of Technology, Mandya', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E232', name: 'REVA University, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E235', name: 'M S Ramaiah University (RUAS), Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E237', name: 'PRESIDENCY University, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E238', name: 'Mysuru Royal Institute, Mandya', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E239', name: 'East West College, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E240', name: 'Dayananda Sagar University, Ramanagar', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E241', name: 'KLE Technological University, Hubballi', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E252', name: 'Mysore College of Engineering, Mysore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E254', name: 'A J Institute of Engineering, Mangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E255', name: 'GITAM University, Bangalore Rural', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E256', name: 'RAI TECHNOLOGICAL UNIVERSITY, Bangalore Rural', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E257', name: 'CMR University Main Campus, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E258', name: 'Maharaja Institute of Technology, Mysore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E264', name: 'BASAV ENGINEERING SCHOOL, VIJAYAPURA', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E265', name: 'Jain College of Engineering, Hubballi', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E269', name: 'Jain College Of Research, Belgaum', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E272', name: 'Government Engineering College, Koppal', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E273', name: 'Government Engineering College, Gangavathi', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E274', name: 'Government Engineering College, Hassan', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E275', name: 'R V Institute Of Technology (RVITM), Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E278', name: 'VTU Muddenahalli Campus, Chickkaballapur', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E279', name: 'VTU Belagavi Campus, Belagavi', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E281', name: 'Government Engineering College, Chitradurga', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E283', name: 'University of Mysuru (BIMS), Mysore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E284', name: 'Sri Jayachamarajendra College (SJCE), Mysore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E285', name: 'RV University, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E286', name: 'BGS College of Engineering, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E287', name: 'Vidyashilp University, Bengaluru', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E288', name: 'Garden City University, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E289', name: 'Visvesvaraya Technological University, Kalburgi', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E290', name: 'Visvesvaraya Technological University, Mysuru', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E291', name: 'Government Engineering College, Gadag', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E292', name: 'Government Engineering College, Bidar', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E297', name: 'ADITYA COLLEGE OF ENGINEERING, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E299', name: 'Ghousia Institute for Women, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E300', name: 'AKASH INTITUTE OF ENGINEERING, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E301', name: 'KISHKINDA UNIVERSITY, Ballari', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E302', name: 'AMITY UNIVERSITY, Bangalore Rural', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E303', name: 'GM University, Davangere', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E304', name: 'MIRJI BHARATESH INSTITUTE, Belagavi', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E305', name: 'DR H N NATIONAL COLLEGE, Bengaluru', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E306', name: 'THE CHANAKYA UNIVERSITY, Devanahalli', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E307', name: 'SESHADRIPURAM INSTITUTE, Mysuru', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E308', name: 'CONSTITUENT COLLEGE OF VTU, Chintamani', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E310', name: 'GOVERNMENT ENGINEERING COLLEGE, Arasikere', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E311', name: 'RATHINAM INSTITUTE OF TECHNOLOGY, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E312', name: 'NEW EBENEZER INSTITUTE, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E313', name: 'HARSHA INSTITUTE OF TECHNOLOGY, Bangalore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' },
  { id: 'E314', name: 'CAUVERY COLLEGE OF ENGINEERING, Mysore', pfp: 'college.png', pill1: 'Cutoff 2025', pill2: 'KCET 2025' }
];
